### ISSUE TITLE
How to use obspyck with local files (waveforms/metadata)?

### ISSUE THREAD

**Issue by megies** [megies/obspyck#10]
try "obspyck.py --help":

```
  -f FILES, --files=FILES
     Local files containing waveform data. List of absolute
     paths separated by commas
  --dataless=DATALESS
     Local Dataless SEED files to look up metadata for
     local waveform files. List of absolute paths separated
     by commas
```

so.. something like

`obspyck.py -f /path/to/file1.gse,/some/path/file2.mseed --dataless
/path1/my_stations1.dataless,/path2/my_stations2.dataless`

etc. should work..

**Comment by AntonBiryukov** [comment]
Hello Tobias @megies ,

I was wondering as to how to pass an an input the picks that were previously saved in the local folder . Is it possible to import the picks into an ObsPyck instance with loaded waveforms from the seed files ?


And if yes, what is the preliminary procedure, that is required to make the FocMec to work ( what would be the best source for the takeoff angles for the said picks etc.)

Regards,

Anton.

**Comment by megies** [comment]
Hi Anton,

first of all, did you remove your old comments/questions from this ticket? Please don't do that, that's very bad style and distorts any discussion in here.

Second, I just commited to master you can now use `--event my_file.xml` to load a previously stored event file at startup.

If you have run a location routine, then your event should be populated with arrivals that also have takeoff angels needed for focmec runs. Hitting "do focMec" is indeed only running focmec, but it's doing that searching for a solution with as little as possible polarity errors which is problematic in a single run of focmec and only really feasible looping over several focmec runs with different input parameters.

T

**Comment by AntonBiryukov** [comment]
Hey Tobias @megies ,

I have just registered on GitHub (literally today) and had no questions / comments in the past, neither I deleted anything  from anywhere.
Moreover, I am a very "green" user of both the GitHub and ObsPy / ObsPyck, so the only questions I might ask are still to come :)


Thanks for the suggestions and the quick response !

**Comment by megies** [comment]
Ok, sorry then. I just noticed that the original poster in this issue removed all his questions..

**Comment by AntonBiryukov** [comment]
Will it matter which routine I 'll use for location?

**Comment by megies** [comment]
> It seems that the presence of the magnitude picks and the lack of location throw that error. I have tried setting P and S picks only - no error, works as a charm. After I added the magnitude peaks (obv., no location yet, as I need to figure out how to add the external programs) - it threw the error.

It seems you have incomplete amplitude picks. Obspyck uses peak-to-peak amplitude in raw counts, so you need to set both min and max (left click/right click).

![screenshot from 2015-06-10 10 15 19](https://cloud.githubusercontent.com/assets/1842780/8077867/a6519186-0f59-11e5-8d28-5e772efa66ea.png)

However unless you have some location routine, you won't be able to get the information necessary to run focmec.
To use hypo2000 you need to point obspyck to your `--pluginpath my_plugin_dir`, make a directory `my_plugin_dir/hyp_2000/` and put a file `my_plugin_dir/hyp_2000/bay2000.inp` in there that is your Hypo2000 control file. Of course you need to put your velocity model in there too and some input/output files have to be correctly set (like they are in obspyck, [here](https://github.com/megies/obspyck/blob/master/util.py#L187-L190))

**Comment by megies** [comment]
I'll lock this discussion about hyp2000 here, this doesn't fit the original issue anymore. Open another ticket if you have problems.
