### ISSUE TITLE
obspyck slows down and we have to restart

### ISSUE THREAD

**Issue by sepideh81** [megies/obspyck#15]
Hello there, 
We use the obspyck to manually pick the phases.
As we go through the events the GUI becomes slower and slower and eventually we have to restart .
Can you please help me with this?
Thanks,
Sep Rastin

**Comment by megies** [comment]
> As we go through the events

How do you do that? I'm calling obspyck individually for each event.

**Comment by sepideh81** [comment]
hi Tobias,
we use the GUI to pick the phases from stations that contributed to each
event and then locate the event. but as we finish one event and move to the
next one, it starts getting slower and slower. we have to restart and load
the GUI again.
regards
sepideh

**Comment by megies** [comment]
Like I said, I start obspyck individually for each event I pick, which is the intended usage. No idea why it is getting slower, sorry if I can't help with this..
