### ISSUE TITLE
Exception when running with Obspy 1.x.x

### ISSUE THREAD

**Issue by dylanmikesell** [megies/obspyck#22]
Is this package going to be upgraded to work with the latest obspy? I installed today and tried to run, but got the following:

Traceback (most recent call last):
  File "/usr/local/bin/obspyck.py", line 4346, in <module>
    raise Exception("ObsPy >= 0.11 not supported.")
Exception: ObsPy >= 0.11 not supported.

I am running Obspy 1.0.1. 

It would be awesome to use your program, but not sure how much work it will take to upgrade.

Dylan

**Comment by megies** [comment]
I don't have time and can't be bothered to look into what it takes to make it ObsPy 1.0 compatible right now. Plus, with anaconda it's super easy to have a separate environment for ObsPyck with ObsPy 0.10.x. See [obspy wiki](https://github.com/obspy/obspy/wiki/Installation-via-Anaconda) and especially [the example with pinning](https://github.com/obspy/obspy/wiki/Installation-via-Anaconda#example).

**Comment by dylanmikesell** [comment]
Thanks. I will try the pinning example with ObsPy 0.10.x. If I get time I will look into making it work with 1.0 as well. Maybe it is not a big job.

**Comment by megies** [comment]
@dylanmikesell did you look into this?

**Comment by megies** [comment]
Fixed with #31.

**Comment by megies** [comment]
ObsPy 1.1.0 is out and I released a new ObsPyck through conda-forge channel, so installation is one-line now with Anaconda, see the wiki.
