### ISSUE TITLE
load local event info

### ISSUE THREAD

**Issue by dylanmikesell** [megies/obspyck#24]
Hi,

We have been having success with obspyck and nlloc that past few weeks here in Boise. 

I have been modifying a branch to work with local files and now I have another question. We are storing small SAC files in `event*/` folders. Each event has it's own number with relevant data to that event, e.g. coincidence trigger info, sac files, the local obspyck xml file (yes, we modified obspyck for this), the nlloc files (we move them from tmp to an `event*/nlloc/` folder at the end of self.doNLLoc() ). I know that the local obspyck xml file contains the pick information. If an obspyck file already exists in the event*/ folder, I would like obspyck to read this and plot the previous picks at startup. I have looked through the code and I am unsure where to implement this. Any ideas?

It seems like a I need to create a catalog instance from the local obspyck file. Does that sound right? I am also thinking that I would like to write a similar event file in obspy when we do the coincidence trigger. Write now we use the coincidence trigger to identify events and then write small sac files. It would be cool to either write an obspyck compatible xml file then or assign picks to the SAC headers. Would it be easier if obspyck just loaded pick times from SAC headers rather than from a local obspyck xml file.

Thanks,

Dylan

**Comment by megies** [comment]
You should be able to load a local QuakeML file saved previously from obspyck with `--event /path/to/obspyck_event.xml`.

> I am also thinking that I would like to write a similar event file in obspy when we do the coincidence trigger. Write now we use the coincidence trigger to identify events and then write small sac files. It would be cool to either write an obspyck compatible xml file then or assign picks to the SAC headers.

That's rather an obspy-related question.. Of course you can assemble a `Catalog` object from coincidence trigger output, that cou then could output as a QuakeML file. You would want to create one `Event` per coincidence trigger and fill in the individual stations' triggers as `Pick`s. You could save the resulting `Catalog` as a QuakeML file and load that from within ObsPyck. That's a much more canonical approach than writing stub SAC files with event info in headers. ([look at the last box in this notebook for a start](https://github.com/obspy/docs/blob/master/workshops/2016-03-07_ipgp/06_Event_metadata-with_solutions.ipynb))

In principle this could also be an option for coincidence trigger routine in obspy (something like `..., output="catalog")`). If you venture further in that direction please open an issue at obspy/obspy.

**Comment by tbartholomaus** [comment]
Hi Dylan and Tobias,

It looks like I'm trying to follow the same path as you:
1. Detect events with network coincidence trigger.
2. Create Catalog of events, with one obspy event per detection
3. Read this catalog into obspyck, with a small snippet of locally-stored waveform data from around the time of the detection.
4. Pick arrival times on the network for each "event", then locate using nlloc.
5. Save picks and locations in an "origin," subsidiary to the "event"
6. Have the ability using obspyck, to skip forward and backward through "origin"s in the catalog.  Save the catalog, and be able to reload and review the picks and locations.

I've done steps 1 and 2, with local data, a local stationXML, and local catalog (quakeML).  But haven't yet worked out steps 3 and 4.  Did you?  Any tips?

Many thanks,
Tim

**Comment by megies** [comment]
> Create Catalog of events, with one obspy event per detection
> Read this catalog into obspyck, with a small snippet of locally-stored waveform data from around the time of the detection.
> Pick arrival times on the network for each "event", then locate using nlloc.
> Save picks and locations in an "origin," subsidiary to the "event"

Current workflow in obspyck is:
 - Make one QuakeML file with a single event for each earthquake in your data.
 - obspyck will also always only regard a single Origin per event
 - "stepping through events" you will have to do by calling obspyck on the shell for each event individually



> Have the ability using obspyck, to skip forward and backward through "origin"s in the catalog. 

not implemented..

**Comment by tbartholomaus** [comment]
I see- this is very useful, Tobias.  Thanks.  So one QuakeML for each event.  Each QuakeML file consists of a single Catalog, with a single Event, with a single Origin...

If I get this shell script wrapper written (to step forward and back between events, automatically re-loading obspyck each time), I'll set up a pull request for it.

**Comment by dylanmikesell** [comment]
Hi Tim,

We made it about as far as you and then ran out of time for this
undergrad's summer project. We ended up just using the obspy STA/LTA after
the coincidence trigger plus NLLoc, and we also tried PhasePApy
<https://github.com/austinholland/PhasePApy> to do refined picking (not by
hand), associate phases and locate using a 1D velocity model. (I have some
notes on running NLLoc if you looking for help with that part.)

Dylan
