### ISSUE TITLE
Obspyck deprecation warnings 

### ISSUE THREAD

**Issue by klaaur** [megies/obspyck#25]
Hello,

Upon downloading the obspyck zip file and attempting to run obspyck.py I get the following warning messages:

>> python obspyck.py 
/usr/local/lib/python2.7/site-packages/obspy/__init__.py:159: ObsPyDeprecationWarning: Module 'obspy.core.util.geodetics' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.geodetics' instead.
  ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py:57: ObsPyDeprecationWarning: Function 'obspy.geodetics.gps2DistAzimuth' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.geodetics.base.gps2dist_azimuth' instead.
  warnings.warn(msg, ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/__init__.py:159: ObsPyDeprecationWarning: Module 'obspy.fdsn' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.fdsn' instead.
  ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/__init__.py:159: ObsPyDeprecationWarning: Module 'obspy.arclink' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.arclink' instead.
  ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/__init__.py:159: ObsPyDeprecationWarning: Module 'obspy.seishub' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.seishub' instead.
  ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py:57: ObsPyDeprecationWarning: Function 'obspy.core.util.gps2DistAzimuth' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.geodetics.gps2dist_azimuth' instead.
  warnings.warn(msg, ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py:57: ObsPyDeprecationWarning: Function 'obspy.core.util.getMatplotlibVersion' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.core.util.get_matplotlib_version' instead.
  warnings.warn(msg, ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py:57: ObsPyDeprecationWarning: Function 'obspy.core.util.locations2degrees' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.geodetics.locations2degrees' instead.
  warnings.warn(msg, ObsPyDeprecationWarning)
/usr/local/lib/python2.7/site-packages/obspy/__init__.py:159: ObsPyDeprecationWarning: Module 'obspy.xseed' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.io.xseed' instead.
  ObsPyDeprecationWarning)
Traceback (most recent call last):
  File "obspyck.py", line 4339, in <module>
    raise Exception("ObsPy >= 0.11 not supported.")
Exception: ObsPy >= 0.11 not supported.

Will another version of Obspyck supporting the current version of ObsPy 1.0.2 be coming out anytime soon? Are there any suggested work arounds? 

Thank you!

**Comment by megies** [comment]
I don't have time or a lot of motivation to work on this right now (see #22). With Anaconda it's super simple to keep a dedicated environment for ObsPyck with ObsPy 0.10, see our wiki: https://github.com/obspy/obspy/wiki/Installation-via-Anaconda#example

**Comment by klaaur** [comment]
Thanks. That allowed me to get it up and running. However, I'm not able to connect to the server_fdsn_iris. I get a socket timeout error. I'm able to connect regularly via obspy to these servers and am wondering what the issue might be. Note I am trying to connect via a proxy server. I have tried setting the proxy servers in the .condarc file as well as in my environment variables or via the command line and I am unable to connect. Any ideas what the issue might be? Thanks.

**Comment by megies** [comment]
No idea.. never had to work with a proxy for this. You could try to set `debug = true` in the config section for the FDSN server to see more output, though (in your `obspyckrc` file), maybe you'll see some messages that help..

**Comment by klaaur** [comment]
I was able to figure out that it was with arc link. Probably something on our end with .eu servers. I ended up setting debug=True to determine where the issue was. Is there a location to describe what the focmec bash script and input files look like from issue #12 ? Also, where do hypo2000 and NonLinLoc need to be to get them up and running? Seishub as well? I've got the GUI going now with examples but the functionality isn't there for the above programs.

**Comment by megies** [comment]
> Is there a location to describe what the focmec bash script and input files look like from issue #12 ?

As you said, please check out #12, there's an example setup for focmec in https://github.com/megies/obspyck/tree/master/plugin_dir/focmec



> Also, where do hypo2000 and NonLinLoc need to be to get them up and running?

Please see #11 for nonlinloc and #16 for hyp2000.



> Seishub as well?

Check out the information at barsch/seishub, and also be aware of what we use as a successor at [krischer/jane](https://github.com/krischer/jane/).

**Comment by megies** [comment]
Fixed with #31.
