### ISSUE TITLE
Question abot run Obspyck

### ISSUE THREAD

**Issue by rcabdia** [megies/obspyck#26]
Hello Master, I am trying to run Obspyck, but when I try to run the obspyck.py something is wrong and the computer says that it is related with the version of obspy;

  File "obspyck.py", line 4339, in <module>
    raise Exception("ObsPy >= 0.11 not supported.")
Exception: ObsPy >= 0.11 not supported.

What is true because I have obspy  1.0.2 in python 2.7, so I have also Qt and PyQt 4.8.7.

That means that I have to uninstall obspy and install a lower version or exits another solution

Thanks for your help

**Comment by megies** [comment]
See #22 this has been asked before several times. Right now you have to have a separate Python environment with ObsPy 0.10.

**Comment by megies** [comment]
Fixed with #31.

**Comment by lplaura** [comment]
Hi!

I am having some trouble to install obspyck with obspy1.0
The dependencies seem to be:
    matplotlib
    numpy
    obspy 1.*
    pyqt
    python 2.7*
    scipy

As my obspy1.0 is working with python3.5, I created a new anaconda environment with python2.7 and installed obspy1.0 and then obspyck. When I tryed to run obspyck I got:

(obspy4obspyck) kl-15141:~ parisil$ obspyck
Traceback (most recent call last):
  File "/Users/parisil/anaconda/envs/obspy4obspyck/bin/obspyck", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/parisil/anaconda/envs/obspy4obspyck/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/Users/parisil/anaconda/envs/obspy4obspyck/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Users/parisil/anaconda/envs/obspy4obspyck/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/parisil/anaconda/envs/obspy4obspyck/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/parisil/anaconda/envs/obspy4obspyck/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/parisil/anaconda/envs/obspy4obspyck/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'obspy>1.0.3' distribution was not found and is required by obspyck

However, I cannot see any obspy>1.0.3 available from anaconda. I am using a osx-64.

I wanted to try with obspy0.10 but from anaconda is not available for osx-64.

How could I solve this? Thanks!

**Comment by megies** [comment]
@lplaura current master branch of obspyck also needs a current obspy master.. i know that actually there is no clean version obspy>1.0.3 but at least this way people know that there is a version issue.

Only way to run current obspyck master at the moment:
 * make dedicated conda env (at least recommended)
 * install current obspy master
 * download/clone current obspyck and comment out the `obspy>1.0.3` line in `setup.py`

Sorry for the inconvenience but there's no really clean way to get this right currently..

**Comment by lplaura** [comment]
No need to be sorry... just a bit of patience with me is fine! ;)

I realised that even though I had created the env with python=2.7 and obspy1.0, obspy was not actually working (the test suite fails).

I tried both in my mac and in a linux machine but I could not make obspy1.0 working with python2.7. On the other hand, obspyck cannot work with python3.5. -.- Is there somewhere a list of package combination to make obspy1.0 working with python2.7 or some other solution? Thanks!

**Comment by megies** [comment]
@lplaura obspy definitely works with python 2.7, see https://github.com/obspy/obspy/wiki/Installation-via-Anaconda

**Comment by lplaura** [comment]
Not with me :(

I created a new environment with python=2.7. I pinned:
python 2.7.*
obspy 1.*
and installed obspy (getting 1.0.2). The tests failed. See log attached (obspy1.0.2_py27)
[obspy1.0.2_py27.pdf](https://github.com/megies/obspyck/files/759900/obspy1.0.2_py27.pdf)

Then, I pinned obspy1.0.1. Same story (log obspy1.0.1_py27)
[obspy1.0.1_py27.pdf](https://github.com/megies/obspyck/files/759901/obspy1.0.1_py27.pdf)

Then, I pinned obspy1.0.0. Same story (log obspy1.0.1_py27)
[obspy1.0.0_py27.pdf](https://github.com/megies/obspyck/files/759902/obspy1.0.0_py27.pdf)

Perhaps I should ask this in the obspy page?

**Comment by megies** [comment]
> and installed obspy (getting 1.0.2). The tests failed. See log attached (obspy1.0.2_py27)
> obspy1.0.2_py27.pdf

That installation looks pretty OK. The main problem with running the tests is that package `mock` is needed to run the tests and it is not installed (just do: `$ conda install mock`). The plot tests fails are likely due to matplotlib 2.0.. if you do `$ obspy-runtests --keep-images` you can check those images.. but it's probably easiest to just pin matplotlib to 1.5 (see obspy/obspy#1616)

**Comment by lplaura** [comment]
great! thanks!

**Comment by megies** [comment]
ObsPy 1.1.0 is out and I released a new ObsPyck through conda-forge channel, so installation is one-line now with Anaconda, see the wiki.
