### ISSUE TITLE
'show Wadati' plot error

### ISSUE THREAD

**Issue by klaaur** [megies/obspyck#28]
After picking my S-P times, example of pTimes,spTimes below

i am pTimes, spTimes
[921.42, 960.828, 776.288, 772.298, 659.523] [1012.0, 1358.555182, 554.04, 620.95, 268.65]

I get the following traceback error:

Traceback (most recent call last):
  File "obspyck.py", line 543, in on_qToolButton_showWadati_toggled
    self.drawWadati()
  File "obspyck.py", line 2877, in drawWadati
    if self.origin.time:
AttributeError: 'ObsPyck' object has no attribute 'origin'

The plot still appears, but the origin time for the event location and the axis labels don't. I tried pushing the 'show Wadati' button after locating my event with nlloc and so I assumed there would be an origin time associated to the event being that the 'show Map' feature is working and provides the origin time.

**Comment by megies** [comment]
I didn't use that plot in ages, it's still implemented as before #9 which was a massive rehaul..

`self.origin` should be something like `self.catalog[0].origins[0]` now..

**Comment by klaaur** [comment]
Replacing lines 2832, 2833:

if self.origin.time:
            otime = "%.3f" % self.origin.time.timestamp

with

if self.catalog[0].origins[0].time:
            otime = "%.3f" % self.catalog[0].origins[0].time.timestamp

does the trick, thanks. I thought it might be within self.catalog[0] but wanted to verify it was the correct origin.
