### ISSUE TITLE
Requires Obspy 1.1.0

### ISSUE THREAD

**Issue by sph1r17** [megies/obspyck#40]
Hi,

I'm a little confused., 

Obspyck requires Obspy version >1.1.0, however, I do not know where to find this.

The current version available via Anaconda is only Obspy 1.0.3. 

Could you please clarify.

I'm using Mac OSX.

**Comment by megies** [comment]
Current obspyck also needs an installation of obspy of the current `master` branch. I.e. there currently is no obspy release version that satisfies this requirement. This is impossible to ensure via setup.py but by specifying a not yet existing release at least users know that there is something problematic.

Way to go currently: Install a developer snapshot of current obspy master branch (I would always recommend to create a separate environment), then download or clone obspyck from github, comment out the line in setup.py with `'obspy>=1.1.0',` and install with pip.

**Comment by sph1r17** [comment]
Many thanks - this now works and I'm very impressed with Obspyck

For some reason, the tick marks along the time axis are appearing, but there are no time axis labels ...
![screen shot 2017-02-24 at 09 58 25](https://cloud.githubusercontent.com/assets/25796081/23299035/e7e0e48e-fa77-11e6-8d4f-af9568e90084.png)

**Comment by megies** [comment]
> Many thanks - this now works and I'm very impressed with Obspyck

Good to hear it works..

> For some reason, the tick marks along the time axis are missing and there are no time axis labels ...

No idea what the problem is.. what matplotlib version are you using? You could try a different one..

**Comment by sph1r17** [comment]
Okay, so I loaded in fours traces and the time axes appears for three of the windows. This is fine and suits my needs, so I consider this closed. Thank you for your help.

**Comment by megies** [comment]
ObsPy 1.1.0 is out and I released a new ObsPyck through conda-forge channel, so installation is one-line now with Anaconda, see the wiki.
