### ISSUE TITLE
Reading multiple picks for continuous data

### ISSUE THREAD

**Issue by sph1r17** [megies/obspyck#42]
Tobias

It seems that when reading in waveform data and an xml file containing picks, it seems that obspyck will only read in one P-pick and one S-pick per station. Of course this understandable for most event location purposes.

However, I'd like to look at picker performance before event association is done. Therefore, I'd like to import continuous waveform data (e.g. 24 hours) that contains multiple (i.e. >2) picks per station.

Is it possible to override the max no. picks limiter in obspyck?

**Comment by megies** [comment]
I've added a switch to allow this.. use at your own risk.. not sure what happens when you start modifying/deleting/adding picks or output to quakeml again.

**Comment by sph1r17** [comment]
Works perfectly - thanks.
