### ISSUE TITLE
relative import error (obspyck installation)

### ISSUE THREAD

**Issue by aozbakir** [megies/obspyck#46]
Hello Tobias and users,

Firstly thanks for developing and making available such software!

I have a problem. I want to use obspyck. Got the package via git clone.
My system (Linux debian 3.16.0-4-686-pae #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) i686 GNU/Linux) satisfies all the dependencies listed under the wiki page.
When I give exec permissions to obspyck and run it I get the following error:

dali@debian:~/obspyck$ ./obspyck/obspyck.py 
Traceback (most recent call last):
  File "./obspyck/obspyck.py", line 53, in <module>
    from . import __version__
ValueError: Attempted relative import in non-package

The error does not change whether I call the exec from the top level package dir or within the same level.
I google a bit for the problem. Relative errors seems to be a common problem for other software too. Can you help me out? 

Cheers, ali

**Comment by megies** [comment]
Sorry there have been quite a few changes that may not be reflected in the wiki.. you should `$ pip install` the git checkout, also see #40, for current obspyck master you'll need a current obspy master (I recommend a dedicated anaconda environment for obspyck).

**Comment by megies** [comment]
I've updated installation section in the wiki..

**Comment by megies** [comment]
I'm closing this now, feel free to reopen if you still have problems.
