### ISSUE TITLE
Matplotlib version

### ISSUE THREAD

**Issue by shicks-seismo** [megies/obspyck#57]
Hi Tobias

So I'm trying a fresh install of Obspyck. I have installed the current Master version of Obspy. 

When I try to start Obspyck, I get the following error: 

> ImportError: cannot import name get_matplotlib_version

Has something changed in the most recent development version of Obspy that doesn't support this function?

**Comment by megies** [comment]
Myeah.. we changed a few things in the dependency version lookups, see obspy/obspy#1734.. should be fixed on master with 751f382d99b3b3030b91f104a7b6532997491809, let me know if there's still a problem.

**Comment by shicks-seismo** [comment]
Working great - thanks!
