### ISSUE TITLE
Obspyck usage

### ISSUE THREAD

**Issue by dmarden** [megies/obspyck#62]
Hi everyone, 

I would like to know if there is any writen manual, guide or tutorial on how to use obspyck. I would like to use it for teaching earthquake location assuming that I can get it to work.

I was able to install the obspyck (master) and obspy (master) into my conda env. One of the questions I have regarding installation is if Seishub or other database is needed.

Also assuming my installation is complete and working (big if), how do I open the main obspyck window. I tried running the command python obspyck.py on my conda env (from different directories in case it was not on my python path) without any success. I'm fairly new with python, so that might be a pretty ridiculous question, apologies in advance.

I appreciate any information
Best
Diego

**Comment by megies** [comment]
You don't need seishub. Some features like downloading/uploading events are seishub specific, but you can still work with local QuakeML files (i.e. load a local QuakeML file and/or save event to local QuakeML file).

You can also load waveforms and station metadata from local files, just pass them along as arguments.

If you're on the recent obspyck master then installation via anaconda should have added an executable called `obspyck`, so when your env is activated you should be able to just run `$ obspyck ...`.

**Comment by megies** [comment]
Would be nice to have this in the wiki, @shicks-seismo! Anybody has the rights to edit it, so would be great if you added it.

**Comment by dmarden** [comment]
@megies - Thanks I was able to run obspyck, I appreciate the help

@shicks-seismo - The guide is really useful, thank you

**Comment by megies** [comment]
Updated the wiki, I think this can be closed.
