### ISSUE TITLE
Update link on the wiki page

### ISSUE THREAD

**Issue by tbartholomaus** [megies/obspyck#76]
Hi Tobias,

Thanks for maintaining this package.  I noticed an obsolete link in the Wiki.  At the bottom of the page, under dependencies, the link for NLLoc should be http://alomax.free.fr/nlloc/, not the existing link to the v5.0 package.

Cheers

**Comment by megies** [comment]
Thanks, fixed. Very likely that's not the only obsolete thing in the wiki, unfortunately though..

**Comment by tbartholomaus** [comment]
:)

Thanks Tobias.

Also, I’m trying to figure out more of a workflow for use of obspyck.  I’ve got data on a local computer, with a station.xml file, and a set of obspy events I’ve created from STA/LTA detections.

I’ve got obspy up and running, which is really pretty nice, but I’m trying to figure out how I can skip from one event to the next, to actually make specific picks on channels for each event.  How can I use the “get Next Event” and other buttons to do this?

I’m launching obspyck with this command:
obspyck /Users/timb/RESln/LemonCrk_GHT/Seis_analysis/DATA/BB*.LM..HH*.2017.196 ../Lemon_station.xml -t 2017-07-15T12:00:00 -d 7200 --event=events.xml

This all seems to work just fine, but I can’t see any recognition of the events in events.xml

These are the messages I’m getting:
Traceback (most recent call last):
  File "/Users/timb/anaconda3/envs/obspyckenv/lib/python2.7/site-packages/obspyck/obspyck.py", line 600, in on_qToolButton_getNextEvent_clicked
    self.updateEventListFromSeisHub(self.T0, self.T1)
  File "/Users/timb/anaconda3/envs/obspyckenv/lib/python2.7/site-packages/obspyck/obspyck.py", line 4509, in updateEventListFromSeisHub
    self.checkForSysopEventDuplicates(self.T0, self.T1)
  File "/Users/timb/anaconda3/envs/obspyckenv/lib/python2.7/site-packages/obspyck/obspyck.py", line 4537, in checkForSysopEventDuplicates
    events = self.event_server.event.get_list(min_last_pick=starttime,
AttributeError: 'NoneType' object has no attribute 'event'

[also- better form to ask this question through github?  I can so that others could see the result…]

Thanks again, this looks like nice software.
Tim

On Jun 19, 2018, at 12:56 AM, Tobias Megies <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, fixed. Very likely that's not the only obsolete thing in the wiki, unfortunately though..

**Comment by megies** [comment]
This is off topic, please open a new ticket with a reasonable name for this.
