### ISSUE TITLE
Getting started with obspyck

### ISSUE THREAD

**Issue by kgo2105** [megies/obspyck#90]
Hi there,

I have downloaded obspyck but am having trouble getting the GUI to open. I first activate:
$ source activate obspyck

then when I enter the following line of code 

$ obspyck -t 2014-11-21T15:00 -d 3600 /Users/Kira/anaconda2/envs/2014.325.00.00.00.0000.XN.SP01..EHZ.M.SAC /Users/Kira/anaconda2/envs/XN_201411210000.xml

I get this error:

Running ObsPyck version 0.6.0 (location: /Users/Kira/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.pyc)
using config file: /Users/Kira/.obspyckrc
================================================================================
Reading local files:
--------------------------------------------------------------------------------
/Users/Kira/anaconda2/envs/2014.325.00.00.00.0000.XN.SP01..EHZ.M.SAC: Waveforms
/Users/Kira/anaconda2/envs/XN_201411210000.xml: Metadata
================================================================================
Fetching waveforms and metadata from servers:
--------------------------------------------------------------------------------
================================================================================
/Users/Kira/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py:241: UserWarning: Cannot find external programs dir, localization methods/functions are deactivated
  warnings.warn(msg)
Traceback (most recent call last):
  File "/Users/Kira/anaconda2/envs/obspyck/bin/obspyck", line 8, in <module>
    sys.exit(main())
  File "/Users/Kira/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 4869, in main
    obspyck = ObsPyck(clients, streams, options, KEYS, config, inventories)
  File "/Users/Kira/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 244, in __init__
    self.info('Using temporary directory: ' + self.tmp_dir)
AttributeError: 'ObsPyck' object has no attribute 'tmp_dir'

I've read through other issue reports and haven't been able to solve this. Thanks for any help you can give.

**Comment by megies** [comment]
Set `pluginpath` in your `.obspyckrc`, I guess it could be the path to an empty directory as long as you don't use external programs.

**Comment by kgo2105** [comment]
Thank you very much for your help with this! I got obspyck up and running.
